=== koselnik/gameshare/games.dtd
<!ELEMENT games (game+)>

<!ELEMENT game (game_id, game_name, created_at, created_by, image, rating, description, category)>
<!ELEMENT game_id (#PCDATA)>
<!ELEMENT game_name (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT created_by (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>

=== koselnik/gameshare/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE games SYSTEM "games.dtd">
<?xml-stylesheet type="text/xsl" href="index.xsl"?>

<games>
  <game>
    <game_name>Martin</game_name>
    <image>m.h@kth.se</image>
    <rating>0703164598</rating>
    <description>Sällskap</description>
    <category>Hej jag söker efter någon som vill dricka glögg me</category>
    <created_at>131011</created_at>
    <created_by>99</created_by>
    <game_id>99</game_id>
  </game>
</games>
